version: '3.1'

services:
  db:
    image: postgres:12-alpine
    container_name: notez_db
    network_mode: host
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
